version: "3"
services:
  cache:
    image: cash
    restart: always
    networks:
      - webappnetwork
    environment: 
      - EXPIRY=1000
      - GODEBUG=madvdontneed=1
  redis:
    image: redis
    restart: always
    expose:
      - 6379
    networks:
      - webappnetwork
  api:
    image: webapp-api
    build: ./api/
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
